language: csharp
dotnet: 2.1.502
solution: TddWithInvariants.sln
os: windows
env:
  global:
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
script:
  - dotnet tool install --global coverlet.console
  - dotnet build TddWithInvariants.sln -c Release
  - dotnet test -c Release --no-build ./Clocks.Tests/Clocks.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover 
after_script:
  - codecov -f coverage.json
#  - bash <(curl -s https://codecov.io/bash) 
