image: Visual Studio 2017
branches:
  only:
  - master

init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: TddWithInvariants.sln
  verbosity: minimal

test_script:
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\Clocks.Tests\bin\Debug\netcoreapp2.1\Clocks.Tests.dll
 -noshadow" -filter:"+[UnitTestTargetProject*]* -[MyUnitTests*]*" -output:".\TddWithInvariants_coverage.xml"
- codecov -f "TddWithInvariants_coverage.xml"
