image: Visual Studio 2017
branches:
  only:
  - master

init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true

before_build:
- nuget restore
- nuget install OpenCover -OutputDirectory packages -Version 4.6.519

build:
  project: TddWithInvariants.sln
  verbosity: minimal

test_script:
- .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full .\Clocks.Tests\Clocks.Tests.csproj" -output:"coverage.xml" -filter:"+[Clocks*]* -[*.Tests]*" -oldstyle
#- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\Clocks.Tests\bin\Debug\netcoreapp2.1\Clocks.Tests.dll
#-noshadow" -filter:"+[UnitTestTargetProject*]* -[MyUnitTests*]*" -output:".\TddWithInvariants_coverage.xml"
- codecov -f "TddWithInvariants_coverage.xml"
